"use client";

export type LineCircleCommand =
  | {
      type: "line";
      x1: number;
      y1: number;
      x2: number;
      y2: number;
      strokeWidth?: number;
    }
  | {
      type: "circle";
      cx: number;
      cy: number;
      r: number;
      strokeWidth?: number;
    };

export type LineCircleDrawingData = {
  width: number;
  height: number;
  commands: LineCircleCommand[];
};

function clamp(value: number, min: number, max: number) {
  return Math.min(Math.max(value, min), max);
}

export default function LineCircleDrawing({ drawing }: { drawing: LineCircleDrawingData }) {
  const width = Math.max(1, drawing.width);
  const height = Math.max(1, drawing.height);

  return (
    <div className="flex w-full flex-col gap-3 rounded-lg border border-gray-200 bg-white p-4">
      <div className="flex items-center justify-between gap-3">
        <p className="text-sm font-semibold text-gray-700">LLM line-circle recreation</p>
        <p className="text-xs text-gray-500">{drawing.commands.length} commands</p>
      </div>
      <div className="w-full overflow-hidden rounded-md border border-gray-200 bg-gray-50">
        <svg
          role="img"
          aria-label="Line and circle drawing generated by the LLM"
          viewBox={`0 0 ${width} ${height}`}
          className="h-auto w-full"
        >
          <rect x="0" y="0" width={width} height={height} fill="white" />
          {drawing.commands.map((command, index) => {
            const strokeWidth = clamp(command.strokeWidth ?? 3, 1, 16);
            if (command.type === "line") {
              return (
                <line
                  key={index}
                  x1={clamp(command.x1, 0, width)}
                  y1={clamp(command.y1, 0, height)}
                  x2={clamp(command.x2, 0, width)}
                  y2={clamp(command.y2, 0, height)}
                  stroke="black"
                  strokeLinecap="round"
                  strokeWidth={strokeWidth}
                />
              );
            }

            return (
              <circle
                key={index}
                cx={clamp(command.cx, 0, width)}
                cy={clamp(command.cy, 0, height)}
                r={clamp(command.r, 1, Math.max(width, height))}
                fill="none"
                stroke="black"
                strokeWidth={strokeWidth}
              />
            );
          })}
        </svg>
      </div>
      <pre className="max-h-48 overflow-auto rounded-md bg-gray-950 p-3 text-xs text-gray-100">
        {JSON.stringify(drawing.commands, null, 2)}
      </pre>
    </div>
  );
}
